# Generated by Django 3.1.6 on 2021-04-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20210222_2352'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ManyToManyField(related_name='stories_image', to='media.Media'),
        ),
    ]
